// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/jocker/pkg/client/pb/jockerdpb"
)

var (
	FakeReturnContainer = &jockerdpb.Container{}
)

type ContainerGetter interface {
	Container() ContainerInterface
}

type ContainerInterface interface {
	Container(ctx context.Context, param *jockerdpb.Empty) (*jockerdpb.Container, error)
}

type FakeContainer struct {
	Fake *FakeJocker
}

func (f *FakeContainer) Container(ctx context.Context, param *jockerdpb.Empty) (*jockerdpb.Container, error) {
	return FakeReturnContainer, nil
}
