// Code generated by goctl. DO NOT EDIT.
// Source: jocker.proto

package server

import (
	"context"

	"github.com/jaronnie/jocker/jockerd/internal/logic"
	"github.com/jaronnie/jocker/jockerd/internal/svc"
	"github.com/jaronnie/jocker/jockerd/jockerdpb"
)

type JockerdServer struct {
	svcCtx *svc.ServiceContext
	jockerdpb.UnimplementedJockerdServer
}

func NewJockerdServer(svcCtx *svc.ServiceContext) *JockerdServer {
	return &JockerdServer{
		svcCtx: svcCtx,
	}
}

func (s *JockerdServer) ServerVersion(ctx context.Context, in *jockerdpb.Empty) (*jockerdpb.ServerVersionResponse, error) {
	l := logic.NewServerVersionLogic(ctx, s.svcCtx)
	return l.ServerVersion(in)
}

func (s *JockerdServer) Container(ctx context.Context, in *jockerdpb.Empty) (*jockerdpb.Container, error) {
	l := logic.NewContainerLogic(ctx, s.svcCtx)
	return l.Container(in)
}
