// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/jocker/pkg/client/typed"
	"github.com/jaronnie/jocker/pkg/client/typed/fake"
	jocker "github.com/jaronnie/jocker/pkg/client/typed/jocker"
	fakejocker "github.com/jaronnie/jocker/pkg/client/typed/jocker/fake"
)

type Clientset struct{}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

func (f *Clientset) Jocker() jocker.JockerInterface {
	return &fakejocker.FakeJocker{}
}
