// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package client

import (
	"github.com/jaronnie/jocker/pkg/client/rest"
	"github.com/jaronnie/jocker/pkg/client/typed"
	jocker "github.com/jaronnie/jocker/pkg/client/typed/jocker"
)

type Interface interface {
	Direct() typed.DirectInterface

	Jocker() jocker.JockerInterface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	jocker *jocker.JockerClient
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) Jocker() jocker.JockerInterface {
	return x.jocker
}

func NewClientWithOptions(ops ...rest.Opt) (*Clientset, error) {
	c := &rest.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.jocker, err = jocker.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return &cs, nil
}
